---
title: "Workshop 02"
author: "Paule Mathieu"
format: html
editor: source
output: 
 html_document:
    code_folding: show
    collapse: no
    df_print: paged
    fig_caption: yes
    fig_height: 6
    fig_width: 10
    highlight: textmate
    theme: spacelab
    toc: yes
    toc_float: yes
editor_options: 
  chunk_output_type: inline
---

## Workshop 02 - Advanced data wrangling (extracting ecological signals from noisy systems)

```{r setup, include=FALSE}
# Set options, housekeeping
knitr::opts_chunk$set(
	echo = FALSE,
	include = TRUE,
	message = FALSE,
	warning = FALSE)
```

## Introduction
This workshop of *R for Marine Science* builds on fundational programming and data wrangling skills, focusing on extracting meaningful biological patterns from complex ecological datasets.


### Clear out environment
```{r housekeeping, message=FALSE, warning=FALSE, include=FALSE}
rm(list=ls())
```

### Load packages
```{r packages, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
```

